In [1]:
import numpy as np

In [29]:
x = [1, 2, 3]
x = np.array(x)

In [18]:
y = np.array([4,5,6])

In [3]:
lis = np.array([[1,2,3], [4, 5, 6]])

In [4]:
lis[1][2]

6

In [5]:
n = np.arange(0, 30, 2)

In [6]:
n= n.reshape(5, 3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [7]:
o = np.linspace(0, 4 , 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [8]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [30]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
np.ones((1, 5))

array([[1., 1., 1., 1., 1.]])

In [10]:
np.zeros((1, 5))

array([[0., 0., 0., 0., 0.]])

In [13]:
p =np.ones((2, 3), int) 

In [14]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [31]:
x+y

array([5, 7, 9])

In [32]:
x*y

array([ 4, 10, 18])

In [33]:
x**2

array([1, 4, 9], dtype=int32)

In [34]:
x.dot(y)

32

In [46]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [47]:
z.shape

(2, 3)

In [48]:
z.T.shape

(3, 2)

In [49]:
z.dtype

dtype('int32')

In [50]:
z = z.astype('f')
z.dtype

dtype('float32')

In [51]:
a = np.array([-4, -3, 0, 1, 2, 5, 3])

In [53]:
a.sum(), a.min(), a.max(), a.mean(), np.median(a), a.std()

(4, -4, 5, 0.5714285714285714, 1.0, 2.9692299558323607)

In [57]:
a.argmax(), a.argmin()

(5, 0)

## Indexing/Slicing

In [59]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [66]:
# last four elements of the array
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [67]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [69]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
r[3, 3:6]

array([21, 22, 23])

In [71]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [73]:
r[-1, ::2]

array([30, 32, 34])

In [75]:
# conditional indexing
r[r>30]

array([31, 32, 33, 34, 35])

In [78]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [80]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [82]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Iterating Over Arrays

In [85]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 8, 0],
       [1, 3, 8],
       [5, 6, 6],
       [1, 7, 8]])

In [86]:
for row in test:
    print(row)

[6 8 0]
[1 3 8]
[5 6 6]
[1 7 8]


In [87]:
for i in range(len(test)):
    print(test[i])

[6 8 0]
[1 3 8]
[5 6 6]
[1 7 8]
